services:
  macros-backend:
    build: 
      context: ./macros-backend
    ports:
      - 3030:3030
    volumes: 
      - C:\Users\roman\.aws\credentials:/root/.aws/credentials:ro
      - C:\Users\roman\.aws\config:/root/.aws/config:ro
    develop:
      watch:
       - path: ./macros-backend
         action: sync
       - path: ./macros-backend/go.*
         action: rebuild
  macros-client:
    build: 
      context: ./macros-client
    ports:
      - 8080:8080
    develop:
      watch:
       - path: ./macros-client
         action: sync
       - path: ./macros-client/package*.json
         action: rebuild