services:
  macros-backend:
    build: 
      context: ./macros-backend
    ports:
      - 3030:3030
    volumes: 
      - ~/.aws/credentials:/root/.aws/credentials:ro
      - ~/.aws/config:/root/.aws/config:ro
    develop:
      watch:
       - path: ./macros-backend
         action: sync
       - path: ./macros-backend/go.*
         action: rebuild
  macros-client:
    build: 
      context: ./macros-client
    command: npm run web
    ports:
      - 8080:8080
    develop:
      watch:
       - path: ./macros-client
         target: /app
         action: sync
         ignore: 
           - node_modules/